{{- if .Values.cadence.tls.enabled }}
{{- if and .Values.cadence.tls.key .Values.cadence.tls.cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benchmark-workers-cadence.fullname" . }}-tls
  labels:
    {{- include "benchmark-workers-cadence.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.cadence.tls.key | b64enc }}
  cert: {{ .Values.cadence.tls.cert | b64enc }}
  {{- if .Values.cadence.tls.ca }}
  ca: {{ .Values.cadence.tls.ca | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
