{{- if .Values.soakTest.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "benchmark-workers.fullname" . }}-soak-test
  labels:
    app: benchmark
    component: soak-test
    {{- include "benchmark-workers.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.soakTest.replicaCount }}
  selector:
    matchLabels:
      app: benchmark
      component: soak-test
      {{- include "benchmark-workers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: benchmark
        component: soak-test
        {{- include "benchmark-workers.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: benchmark-soak-test
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TEMPORAL_GRPC_ENDPOINT
          value: {{ include "benchmark-workers.grpcEndpoints" . | quote }}
        - name: TEMPORAL_NAMESPACE
          value: {{ include "benchmark-workers.namespaces" . | quote }}
        - name: TEMPORAL_TASK_QUEUE
          value: {{ .Values.temporal.taskQueue | quote }}
        - name: CONCURRENT_WORKFLOWS
          value: {{ .Values.soakTest.concurrentWorkflows | quote }}
        {{- if .Values.temporal.tls.enabled }}
        {{- $tlsKeys := include "benchmark-workers.tlsKeys" . }}
        {{- $tlsCerts := include "benchmark-workers.tlsCerts" . }}
        {{- $tlsCas := include "benchmark-workers.tlsCas" . }}
        {{- if or $tlsKeys $tlsCerts $tlsCas }}
        - name: TEMPORAL_TLS_KEY
          value: {{ $tlsKeys | quote }}
        - name: TEMPORAL_TLS_CERT
          value: {{ $tlsCerts | quote }}
        {{- if $tlsCas }}
        - name: TEMPORAL_TLS_CA
          value: {{ $tlsCas | quote }}
        {{- end }}
        {{- else }}
        - name: TEMPORAL_TLS_KEY
          value: "/etc/temporal/tls/key"
        - name: TEMPORAL_TLS_CERT
          value: "/etc/temporal/tls/cert"
        - name: TEMPORAL_TLS_CA
          value: "/etc/temporal/tls/ca"
        {{- end }}
        {{- if .Values.temporal.tls.disableHostVerification }}
        - name: TEMPORAL_TLS_DISABLE_HOST_VERIFICATION
          value: "true"
        {{- end }}
        {{- end }}
        command: 
        - "runner"
        - "-w"
        - "-c"
        - "$(CONCURRENT_WORKFLOWS)"
        - "-t"
        - {{ .Values.soakTest.workflowType | quote }}
        - {{ .Values.soakTest.workflowArgs | quote }}
        {{- if .Values.soakTest.resources }}
        resources:
          {{- toYaml .Values.soakTest.resources | nindent 10 }}
        {{- end }}
        {{- if and .Values.temporal.tls.enabled (not (or (include "benchmark-workers.tlsKeys" .) (include "benchmark-workers.tlsCerts" .) (include "benchmark-workers.tlsCas" .))) }}
        volumeMounts:
        - name: tls
          mountPath: /etc/temporal/tls
          readOnly: true
        {{- end }}
      {{- if and .Values.temporal.tls.enabled (not (or (include "benchmark-workers.tlsKeys" .) (include "benchmark-workers.tlsCerts" .) (include "benchmark-workers.tlsCas" .))) }}
      volumes:
      - name: tls
        secret:
          secretName: {{ if .Values.temporal.tls.existingSecret }}{{ .Values.temporal.tls.existingSecret }}{{ else }}{{ include "benchmark-workers.fullname" . }}-tls{{ end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
{{- end }} 