apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "benchmark-workers.fullname" . }}-workers
  labels:
    app: benchmark
    component: workers
    {{- include "benchmark-workers.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workers.replicaCount }}
  selector:
    matchLabels:
      app: benchmark
      component: workers
      {{- include "benchmark-workers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: benchmark
        component: workers
        {{- include "benchmark-workers.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: benchmark-workers
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.metrics.enabled }}
        ports:
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        {{- end }}
        env:
        - name: TEMPORAL_GRPC_ENDPOINT
          value: {{ .Values.temporal.grpcEndpoint | quote }}
        - name: TEMPORAL_NAMESPACE
          value: {{ .Values.temporal.namespace | quote }}
        - name: TEMPORAL_TASK_QUEUE
          value: {{ .Values.temporal.taskQueue | quote }}
        - name: TEMPORAL_WORKFLOW_TASK_POLLERS
          value: {{ .Values.temporal.workflowTaskPollers | quote }}
        - name: TEMPORAL_ACTIVITY_TASK_POLLERS
          value: {{ .Values.temporal.activityTaskPollers | quote }}
        {{- if .Values.metrics.enabled }}
        - name: PROMETHEUS_ENDPOINT
          value: {{ .Values.metrics.prometheusEndpoint | quote }}
        {{- end }}
        {{- if .Values.temporal.tls.enabled }}
        {{- if and .Values.temporal.tls.key .Values.temporal.tls.cert }}
        - name: TEMPORAL_TLS_KEY
          value: {{ .Values.temporal.tls.key | quote }}
        - name: TEMPORAL_TLS_CERT
          value: {{ .Values.temporal.tls.cert | quote }}
        {{- if .Values.temporal.tls.ca }}
        - name: TEMPORAL_TLS_CA
          value: {{ .Values.temporal.tls.ca | quote }}
        {{- end }}
        {{- else }}
        - name: TEMPORAL_TLS_KEY
          value: "/etc/temporal/tls/key"
        - name: TEMPORAL_TLS_CERT
          value: "/etc/temporal/tls/cert"
        - name: TEMPORAL_TLS_CA
          value: "/etc/temporal/tls/ca"
        {{- end }}
        {{- if .Values.temporal.tls.disableHostVerification }}
        - name: TEMPORAL_TLS_DISABLE_HOST_VERIFICATION
          value: "true"
        {{- end }}
        {{- end }}
        {{- if .Values.additionalEnv }}
        {{- toYaml .Values.additionalEnv | nindent 8 }}
        {{- end }}
        {{- if .Values.workers.resources }}
        resources:
          {{- toYaml .Values.workers.resources | nindent 10 }}
        {{- end }}
        {{- if and .Values.temporal.tls.enabled (not (and .Values.temporal.tls.key .Values.temporal.tls.cert)) }}
        volumeMounts:
        - name: tls
          mountPath: /etc/temporal/tls
          readOnly: true
        {{- end }}
      {{- if and .Values.temporal.tls.enabled (not (and .Values.temporal.tls.key .Values.temporal.tls.cert)) }}
      volumes:
      - name: tls
        secret:
          secretName: {{ if .Values.temporal.tls.existingSecret }}{{ .Values.temporal.tls.existingSecret }}{{ else }}{{ include "benchmark-workers.fullname" . }}-tls{{ end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always 