{{- if .Values.temporal.tls.enabled }}
{{- if and .Values.temporal.tls.key .Values.temporal.tls.cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benchmark-workers.fullname" . }}-tls
  labels:
    {{- include "benchmark-workers.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.temporal.tls.key | b64enc }}
  cert: {{ .Values.temporal.tls.cert | b64enc }}
  {{- if .Values.temporal.tls.ca }}
  ca: {{ .Values.temporal.tls.ca | b64enc }}
  {{- end }}
{{- end }}
{{- end }} 