{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "benchmark-workers.fullname" . }}
  labels:
    app: benchmark
    {{- include "benchmark-workers.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: benchmark
    {{- include "benchmark-workers.selectorLabels" . | nindent 4 }}
{{- end }} 